-- 코드를 입력하세요
SELECT SALES_DATE,	PRODUCT_ID,	USER_ID, SALES_AMOUNT
from ONLINE_SALE
where SALES_DATE >= '2022-03-01' and SALES_DATE < '2022-04-01'
union all
SELECT SALES_DATE,	PRODUCT_ID, null AS USER_ID, SALES_AMOUNT
from OFFLINE_SALE
where SALES_DATE >= '2022-03-01' and SALES_DATE < '2022-04-01'
order by  SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;