-- 코드를 입력하세요
# SELECT r.REST_ID, i.REST_NAME,	i.FOOD_TYPE,	i.FAVORITES,	i.ADDRESS,	round(avg(r.REVIEW_SCORE), 2) as SCORE
# from REST_INFO i join REST_REVIEW r on i.rest_id and r.rest_id
# where i.ADDRESS LIKE '%서울%'
# group by  r.REST_ID
# order by SCORE DESC, i.FAVORITES DESC;

SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, ROUND(AVG(r.REVIEW_SCORE), 2) AS "SCORE"
FROM REST_INFO i JOIN REST_REVIEW r ON i.REST_ID = r.REST_ID 
WHERE i.ADDRESS LIKE '서울%'
GROUP BY i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;