-- 코드를 입력하세요
SELECT p.PRODUCT_ID, PRODUCT_NAME, sum(AMOUNT) * price as TOTAL_SALES
from FOOD_ORDER f join FOOD_PRODUCT p on f.PRODUCT_ID = p.PRODUCT_ID
where PRODUCE_DATE >= '2022-05-01' and PRODUCE_DATE < '2022-06-01'
group by PRODUCT_ID
order by TOTAL_SALES DESC, PRODUCT_ID;