-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
from MEMBER_PROFILE m join REST_REVIEW r on m.MEMBER_ID = r.MEMBER_ID
where m.MEMBER_ID = (select MEMBER_ID from REST_REVIEW group by MEMBER_ID order by count(MEMBER_ID) desc limit 1)
order by REVIEW_DATE ASC, REVIEW_TEXT ASC;